analytics: {}
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.949616
  lightness: 0.197972
  rhythmicContrast: 0.591876
  saturation: 0.742785
cta: {}
layout_spectrum: 0.297297
name: The Wanderer
opengraph: {}
purpose: {}
typography_spectrum: 0.014358
